[package]
name = "iris"
version = "0.1.0"
authors = ["Mike Gedelman <mgedelman@aledade.com>"]
edition = "2018"
build = "build.rs" # LALRPOP preprocessing

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19.4"

[dependencies]
lalrpop-util = "0.19.4"
regex = "1"